// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfkblofwgmtytbsxmksk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZma2Jsb2Z3Z210eXRic3hta3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzM0MTMsImV4cCI6MjA2NzY0OTQxM30.1_OH_rX33epMgHHN-tu1mnvXy-wVHLWSV7fxrelcyKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});